### ISSUE TITLE
Problemas com o Goalkeeper Lab 

### ISSUE THREAD

**Issue by Pedro-RP** [PauloCabral-hub/ResearchCodes#1]
Enquanto tentava rodar o software, me deparei com dois tipos de erros distintos, mas que parecem estar conectados.

1) Erro envolvendo matriz  sem dados de EEG (experimento JG LTPB)

O software abre normalmente quando utilizo os dados do experimento com a LTPB, que consistem em matrizes de 11 colunas, sendo as 9 primeiras dispostas de acordo com o formato padrão exigido pelo software. A décima coluna é o tempo passado total e a décima primeira é o apelido do participante no JG.
Todas as funções do software parecem estar funcionando bem, com exceção das "opções avançadas" que permitem ver a distribuição dos tempos de resposta filtrando entre erros e acertos na jogada anterior. Quando "opções avançadas" está selecionado o seguinte erro aparece:

![60561022-38c5-4cd1-9ded-dfd6775e0249](https://user-images.githubusercontent.com/71903680/232144684-73f4d00e-5420-42c0-9a4a-e0f65244fa9f.jpg)

Exemplo de situação onde o erro ocorre:
![6e79e631-85bd-4e97-832d-d913becaa652](https://user-images.githubusercontent.com/71903680/232144786-7fff6645-e789-4182-a69c-5807d0bfdaca.jpg)

2) Erro envolvendo matriz com dados de EEG

Carreguei o arquivo .set que havia sido compartilhado com a equipe após o treino no neuromat (PDPauloPassos1022_v01filtpreICA.set) no eeaglab ("load existing dataset"). Depois disso rodei a função "to_datamatrix" e o software. O Software abre normalmente, mas não consigo realizar nenhuma operação nele. O erro é o seguinte:

![b685867f-1431-4c0f-8346-78e6bbe23b22](https://user-images.githubusercontent.com/71903680/232145869-cbd9a4a9-783c-4989-8f21-ffc152242051.jpg)

**Comment by PauloCabral-hub** [comment]
Resolução Issue 1a

Origem do erro: double tagging. Cada objeto gráfico do software possui uma 'Tag' que o identifica. O item com a 'Tag' condition apresentava uma etiqueta adicional na linha 120 <120: conditioning.Tag = 'misc3';> do script da função GoalkeeperLab.m. Removendo a linha, o software funciona normalmente para a solicitação descrita.

![issu1a_solution](https://user-images.githubusercontent.com/59887943/232857039-3706a727-9d6d-4f4f-b89b-d0552d67c02f.png)

**Comment by PauloCabral-hub** [comment]
Resolução Issue 1b

Origem do erro: Pode ser que tenha mesma origem do Issue 1b. Um script com o teste e detalhes sobre as etapas foi inserido na repositório issues_scripts: 'issue_number1b_troubleshoot.m'. Seguindo os passos lá descritos o software funcionou adequadamente
![issue1b_solution](https://user-images.githubusercontent.com/59887943/232866523-566b26b6-82e9-4157-b96d-fd4b07608f75.png)
.
