### ISSUE TITLE
Erro ao tentar rodar dados de EMG do Victor

### ISSUE THREAD

**Issue by Pedro-RP** [PauloCabral-hub/ResearchCodes#2]
Importei o conjunto de dados enviados pelo Victor seguindo os passos que estão nas imagens seguintes:

![d1a7dc83-c68f-42f3-993b-d9bbc7cc4f9e](https://user-images.githubusercontent.com/71903680/233168727-79dd6633-88e8-4f76-9463-1ae794b2cf14.jpg)

![767445c4-1505-4a58-a572-0902a866979e](https://user-images.githubusercontent.com/71903680/233168764-d2f92981-fc84-43f6-8baa-c1068dc21fbc.jpg)

![49e75fea-f900-482e-a12a-e209bc32ae33](https://user-images.githubusercontent.com/71903680/233168785-292706ab-f048-4c97-9498-afef7ea1dcd6.jpg)

![6e59d668-7a88-4361-b081-ef73444a311d](https://user-images.githubusercontent.com/71903680/233168844-dad80867-1057-4796-8483-0d6caf6e5d92.jpg)

Ao rodar a função "to_datamatrix" com a correção ativada (último input sendo igual a 1) o erro retratado na imagem referente a linha 78 aparece. Ao rodar com a correção inativada (último input sendo igual a 0) o erro retratado na imagem referente a linha 87 aparece.

![486a2445-3fe7-41f1-baf2-7d929af1ccbd](https://user-images.githubusercontent.com/71903680/233168893-2f599ca2-8122-4a41-bde6-c25104eb4df2.jpg)

Os mesmos erros ocorrem quando salvo o dataset em um arquivo .set e faço o carregamento no eeglab. Além disso, todos os passos descritos no arquivo de troubleshoot da issue 1b foram seguidos.

Se eu tento fazer a importação de dados usando a interface BIOSIG, não aparece erro quando rodo a função "to_datamatrix" com sem a correção (0). No entanto, quando rodo o software do goalkeeper game aparece um erro diferente dos demais.

![b32a1907-4e73-4391-b5ba-de956d9296ce](https://user-images.githubusercontent.com/71903680/233171059-90cecdaa-a8aa-4e0f-b294-fa7a8f595d99.jpg)

![b67f5e0c-43f5-4b2d-9a95-bba462e490d7](https://user-images.githubusercontent.com/71903680/233171102-abab585b-b521-4c87-b126-f07e40b8b317.jpg)

![6e0c6e8a-c164-49a2-b96c-6dd56d2172da](https://user-images.githubusercontent.com/71903680/233171191-0ba282fc-4a72-41a5-b73d-ad51cd3e1dae.jpg)

![531b9aaf-8106-42b2-b270-65a4d0818588](https://user-images.githubusercontent.com/71903680/233171249-f1cc0777-8330-4995-af1f-40b176612b5e.jpg)

**Comment by PauloCabral-hub** [comment]
Origem do erro: Na descrição é repassada à função um número superior ao de trials no conjunto de dados (a quantidade correta é 291). A correção NÃO deve ser aplicada ao conjunto de dados em questão (reproduzir o script "issue_number2_troubleshoot.m" na pasta "issues_script" e ver os comentários). Sendo assim, não houveram modificações a serem realizadas nos códigos.

Observações: É indicado determinar uma regra para os nomes atribuídos aos dados. Além disso, deve-se evitar a utilização dos nomes dos voluntários nessa nomenclatura.
